version: '3.7'
services:
  finlogger:
    container_name: finlogger
    env_file:
      - .env
    build:
      context: .
    restart: on-failure
    networks:
      - main

  celery-redis:
    container_name: celery-redis
    restart: always
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - main
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data/redis
volumes:
  redis-data:
networks:
  main: