# Generated by Django 3.1.6 on 2021-02-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_file_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='prosecure',
            field=models.CharField(default='Unknown', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='code',
            field=models.CharField(default='None', max_length=7, verbose_name='Code'),
        ),
    ]
