# Generated by Django 3.1.6 on 2021-02-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_auto_20210207_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawaltransaction',
            name='uuid',
        ),
    ]
